<template>
  <div class="u-m40 container">
    <div class="bloc" style="margin-top: 165px;">
      <h2 class="u-mb30">Introduction</h2>
      <vue-markdown>{{ schema.info.description }}</vue-markdown>
      <div>
        <div v-if="schema.externalDocs"><br>
          {{ schema.externalDocs.description }}<br>
          <a :href="schema.externalDocs.url">{{ schema.externalDocs.url }}</a>
        </div>
      </div>

      <div class="u-mt40">
        <h2 class="u-mb30">Informations</h2>
        <div v-if="schema.info.termsOfService">You can consult our <a :href="schema.info.termsOfService">Terms Of Service</a></div>
        <div v-if="schema.info.contact">If you need help you can email us at <a :href="`mailto:${schema.info.contact.email}`">{{ schema.info.contact.email }}</a></div>
        <div v-if="schema.info.license">The license of this documentation is <a :href="schema.info.license.url">{{ schema.info.license.name }}</a>, it was generated by <a href="https://github.com/bodinsamuel/api-doc-ui">Api Doc UI</a></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  computed: {
    schema() {
      return this.$store.state.Schema.current;
    },
  },
}
</script>
