<template>
  <div class="u-m40 container">
    <div class="bloc" style="margin-top: 165px;">
      <h2 class="u-mb20">Presentation</h2>
      <vue-markdown class="markdown" :source="schema.info.description"></vue-markdown>
      <div>
        <div v-if="schema.externalDocs"><br>
          {{ schema.externalDocs.description }}<br>
          <a :href="schema.externalDocs.url">{{ schema.externalDocs.url }}</a>
        </div>
      </div>

      <div class="u-mt40">
        <h2 class="u-mb30">Informations</h2>
        <div v-if="schema.info.contact">
          <p>If you need help you can contact us:</p>
          <p v-if="schema.info.contact.url">
            - On our dedicated support page <a :href="schema.info.contact.url">{{ schema.info.contact.url }}</a>
          </p>
          <p v-if="schema.info.contact['x-twitter']">
            - On twitter.com <a :href="`https://twitter.com/${schema.info.contact['x-twitter']}`">@{{ schema.info.contact['x-twitter'] }}</a>
          </p>
          <p v-if="schema.info.contact.email">
            - By email at <a :href="`mailto:${schema.info.contact.email}`">{{ schema.info.contact.email }}</a>
          </p>
          <br>
        </div>
        <p v-if="schema.info.termsOfService">You can consult our <a :href="schema.info.termsOfService">Terms Of Service</a></p>
        <p v-if="schema.info.license">The license of this documentation is <a :href="schema.info.license.url">{{ schema.info.license.name }}</a>, it was generated by <a href="https://github.com/bodinsamuel/api-doc-ui">Api Doc UI</a></p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  head() {
    return {
      title: `${this.schema.info.title} Documentation`,
    };
  },
  computed: {
    schema() {
      return this.$store.state.Schema.current;
    },
  },
};
</script>
